# Generated by Django 3.1.4 on 2020-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=250)),
                ('category_discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=250)),
                ('place_description', models.TextField()),
                ('place_img_1', models.ImageField(default='', upload_to='places')),
                ('place_location', models.CharField(max_length=500)),
            ],
        ),
    ]
