# Generated by Django 3.1.4 on 2020-12-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=250)),
                ('category_discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('place_description', models.TextField()),
                ('place_img_1', models.ImageField(default='', upload_to='places')),
                ('place_img_2', models.ImageField(default='', upload_to='places')),
                ('place_img_3', models.ImageField(default='', upload_to='places')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('place_location', models.CharField(max_length=500)),
                ('place_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour.category')),
            ],
        ),
    ]
