# Generated by Django 3.1.4 on 2020-12-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
