# Generated by Django 3.1.4 on 2020-12-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_img_2',
            field=models.ImageField(default='', upload_to='places'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_img_3',
            field=models.ImageField(default='', upload_to='places'),
        ),
    ]
