# Generated by Django 3.1.4 on 2020-12-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20201211_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=250)),
                ('category_discription', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='place_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tour.category'),
            preserve_default=False,
        ),
    ]
