# Generated by Django 3.1.4 on 2020-12-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0005_auto_20201211_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=250)),
                ('post_content', models.TextField()),
                ('post_img', models.ImageField(default='', upload_to='blogs')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour.category')),
            ],
        ),
    ]
