# Generated by Django 3.1.4 on 2020-12-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0005_auto_20201211_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volenteer',
            fields=[
                ('volunteer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=15)),
                ('img', models.ImageField(default='', upload_to='volunteers')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.place')),
            ],
        ),
    ]
