# Generated by Django 3.1.4 on 2020-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volenteer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
